apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskserviceapiprobes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: taskserviceapiprobes
  template:
    metadata:
      labels:
        app: taskserviceapiprobes
    spec:
     containers:
      - name: taskserviceapiprobes
        image: w8873docker /taskserviceapi			// to use my own docker account
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 80
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 80
          initialDelaySeconds: 5
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: taskservice
spec:
  selector:
    app: taskserviceapiprobes
  ports:
  - port: 80
    targetPort: 80
